// ──────────────────────────────────────────────────────────────────────────────
// The ANTS — Supabase Database Types (Auto-Generated)
// ──────────────────────────────────────────────────────────────────────────────
//
// This file will be auto-generated by the Supabase CLI when transitioning
// from mock data to the live database:
//
//   npx supabase gen types typescript --local > src/types/supabase.ts
//
// For now, it exports a placeholder Database type.
// ──────────────────────────────────────────────────────────────────────────────

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
